//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum CasingOrderTypeEnum : short
    {
        Casing = 0,
        Liner1 = 1,
        Liner2 = 2,
        Liner3 = 3,
        Liner4 = 4,
        Liner5 = 5
    }
}
