//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasingChartLookup
    {
        public int Key { get; set; }
        public double OuterDiameter { get; set; }
        public double Weight { get; set; }
        public string Grade { get; set; }
        public double Collapse { get; set; }
        public Nullable<double> InternalMinYield { get; set; }
        public Nullable<double> JointStrengthSTC { get; set; }
        public Nullable<double> JointStrengthLTC { get; set; }
        public Nullable<double> JointStrengthBTC { get; set; }
        public Nullable<double> BodyYield { get; set; }
        public Nullable<double> Wall { get; set; }
        public double InnerDiameter { get; set; }
        public Nullable<double> DriftDiameterAPI { get; set; }
        public Nullable<double> DriftDiameterSPDR { get; set; }
        public Nullable<double> MaximumSettingDepthSTC { get; set; }
    }
}
