//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cylinder
    {
        public System.Guid Id { get; set; }
        public double MeasuredDepth { get; set; }
        public double InnerDiameter { get; set; }
        public double OuterDiameter { get; set; }
        public double TopOfLiner { get; set; }
        public InterfaceStateTypeEnum InnerInterfaceState { get; set; }
        public InterfaceStateTypeEnum OuterInterfaceState { get; set; }
        public System.Guid WellBoreId { get; set; }
        public double Weight { get; set; }
        public string Grade { get; set; }
        public CasingOrderTypeEnum CasingOrderType { get; set; }
        public double CalculatedVolume { get; set; }
    
        public virtual WellBore WellBore { get; set; }
    }
}
