//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum EventTypeEnum : short
    {
        PumpsUp = 1,
        PumpsDown = 2,
        ShutIn = 3,
        MasterOpen = 4,
        MasterClose = 5,
        EquipmentFailure = 6,
        BallDropped = 7,
        BallSeated = 8,
        LubricatorAttachedToWellhead = 9,
        StartAcid = 10,
        StopAcid = 11,
        FluidChange = 12,
        ProppantChange = 13,
        ScreenOut = 14,
        StartPerfGunsPumpDown = 15,
        StopPerfGunsPumpDown = 16,
        PlugSet = 17,
        PerfFired = 18,
        PerfMisfire = 19,
        Breakdown = 20,
        SeismosActiveShot = 21,
        SeismosActiveShotForward = 22,
        SeismosActiveShotRetraction = 23,
        SeismosEquipmentFailure = 24,
        Other = 25
    }
}
