//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum FilterTypeEnum : short
    {
        BandPass = 1,
        HighPass = 2,
        LowPass = 3,
        PredictiveError = 3,
        BasisProjection = 4,
        CustomNoise = 5,
        Other = 6
    }
}
