//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum FluidTypeEnum : short
    {
        Water = 1,
        SlickWater = 2,
        LinearGel = 3,
        CrosslinkGel = 4,
        N2 = 5,
        CO2 = 6,
        Propane = 7,
        Brine = 8,
        Methane = 9,
        Butane = 10,
        Other = 11
    }
}
