//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fluid
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public FluidTypeEnum Type { get; set; }
        public double Density { get; set; }
        public double BulkModulus { get; set; }
        public double Volume { get; set; }
        public double Viscosity { get; set; }
        public System.Guid HFTreatmentStageId { get; set; }
    
        public virtual HFTreatmentStage HFTreatmentStage { get; set; }
    }
}
