//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class HFTreatmentStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HFTreatmentStage()
        {
            this.Fluids = new HashSet<Fluid>();
            this.Proppants = new HashSet<Proppant>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int StageNumber { get; set; }
        public double TotalVolume { get; set; }
        public System.Guid StageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fluid> Fluids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proppant> Proppants { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
