//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Injection
    {
        public System.Guid Id { get; set; }
        public InjectionTypeEnum Type { get; set; }
        public double Volume { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime StopTime { get; set; }
        public System.Guid InjectionDataAcquisitionId { get; set; }
    
        public virtual InjectionDataAcquisition InjectionDataAcquisition { get; set; }
    }
}
