//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum InjectionTypeEnum : short
    {
        WasteWater = 1,
        Brine = 2,
        CO2 = 3,
        Steam = 4,
        N2 = 5,
        Propane = 6,
        Methane = 7,
        Butane = 8,
        Slickwater = 9,
        LinearGel = 10,
        CrosslinkGel = 11,
        Other = 12
    }
}
