//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public double Density { get; set; }
        public double BulkModulus { get; set; }
    
        public virtual WellheadComponent WellheadComponent { get; set; }
        public virtual Plug Plug { get; set; }
    }
}
