//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamConstraint
    {
        public System.Guid Id { get; set; }
        public double MinimumC1 { get; set; }
        public double MinimumC2 { get; set; }
        public double MinimumC3 { get; set; }
        public double MinimumC4 { get; set; }
        public double MinimumQ1 { get; set; }
        public double MinimumQ2 { get; set; }
        public double MinimumQ3 { get; set; }
        public double MinimumQ4 { get; set; }
        public double MaximumC1 { get; set; }
        public double MaximumC2 { get; set; }
        public double MaximumC3 { get; set; }
        public double MaximumC4 { get; set; }
        public double MaximumQ1 { get; set; }
        public double MaximumQ2 { get; set; }
        public double MaximumQ3 { get; set; }
        public double MaximumQ4 { get; set; }
        public Nullable<System.Guid> UsedParameterId { get; set; }
    
        public virtual UsedParameter UsedParameter { get; set; }
    }
}
