//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum PerforationShapeEnum : short
    {
        Conical = 1,
        Cylindrical = 2,
        Hemispherical = 3,
        Amorphous = 4
    }
}
