//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perforation
    {
        public System.Guid Id { get; set; }
        public double MD { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double Depth { get; set; }
        public PerforationShapeEnum ShapeType { get; set; }
        public System.Guid StageId { get; set; }
    
        public virtual Stage Stage { get; set; }
    }
}
