//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plug
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public double OuterDiameter { get; set; }
        public double OpeningDiameter { get; set; }
        public double TopMD { get; set; }
        public double Length { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
