//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum ProcessingTypeEnum : short
    {
        ReflectionModel = 1,
        PressureDecay = 2,
        ProppedLength = 3,
        KGraph = 4,
        Autocorrelation = 5,
        LongPeriodReflectionModel = 6,
        AllStagesKGraph = 7,
        AllStageAcPlot = 8,
        Other = 9
    }
}
