//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processing
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DataAcquisitionId { get; set; }
        public ProcessingTypeEnum Type { get; set; }
        public string Name { get; set; }
        public System.DateTime ProcessingStartTime { get; set; }
        public System.DateTime LastModified { get; set; }
        public double NearFieldConductivity { get; set; }
        public double C1 { get; set; }
        public double C2 { get; set; }
        public double C3 { get; set; }
        public double C4 { get; set; }
        public double Q1 { get; set; }
        public double Q2 { get; set; }
        public double Q3 { get; set; }
        public double Q4 { get; set; }
        public double FarFieldConductivity { get; set; }
        public int TimeOfMeasurement { get; set; }
        public double EffectivePropperLength { get; set; }
        public double Residual { get; set; }
        public bool Final { get; set; }
    
        public virtual DataAcquisition DataAcquisition { get; set; }
        public virtual UsedParameter UsedParameter { get; set; }
        public virtual KGraphData KGraphData { get; set; }
        public virtual ACGraphData ACGraphData { get; set; }
    }
}
