//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum ProppantTypeEnum : short
    {
        Sand = 1,
        Ceramic = 2,
        ResinCoatedSand = 3,
        ResinCoatedCeramic = 4,
        Conductive = 5,
        Other = 6
    }
}
