//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum ReflectionTypeEnum : short
    {
        FirstCasingJoint = 1,
        SecondCasingJoint = 2,
        ThirdCasingJoint = 3,
        FourthCasingJoint = 4,
        FirstCasingJointMultiple = 5,
        SecondCasingJointMultiple = 6,
        ThridCasingJointMulitple = 7,
        FourthCasingJointMultiple = 8,
        Toe = 9,
        PerfsPlug = 10,
        Plug = 11,
        Mixed = 12,
        Other = 13
    }
}
