//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reflection
    {
        public long Id { get; set; }
        public ReflectionTypeEnum Type { get; set; }
        public double Weight { get; set; }
        public Nullable<long> DataRecordId { get; set; }
    
        public virtual DataRecord DataRecord { get; set; }
        public virtual TimePick StartTimePick { get; set; }
        public virtual TimePick EndTimePick { get; set; }
        public virtual UsedParameter UsedParameter { get; set; }
    }
}
