//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum TimePickTypeEnum : short
    {
        StartActiveShot = 1,
        EndActiveShot = 2,
        StartWirelineWaterHammer = 3,
        EndWirelineWaterHammer = 4,
        StartShutInWaterHammer = 5,
        EndShutInWaterHammer = 6,
        StartPerfWaterHammer = 7,
        EndPerfWaterHammer = 8,
        StartPressureDecay = 9,
        EndPressureDecay = 10,
        StartKGraph = 11,
        EndKGraph = 12,
        StartAcPlot = 13,
        EndAcPlot = 14,
        OtherStart = 15,
        OtherEnd = 16
    }
}
