//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum TreatmentTypeEnum : short
    {
        HydraulicFracturing = 1,
        SteamInjection = 2,
        Acid = 3,
        CasingRepair = 4,
        CleanOut = 5,
        JunkBasket = 6,
        PlugDrillOut = 7,
        PlugRecovery = 8,
        Refrac = 9
    }
}
