//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedFilter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsedFilter()
        {
            this.BasisSets = new HashSet<BasisSet>();
        }
    
        public System.Guid Id { get; set; }
        public FilterTypeEnum Type { get; set; }
        public double LowerFrequency { get; set; }
        public double UpperFrequency { get; set; }
        public string TaperFunction { get; set; }
        public Nullable<System.Guid> UsedParameterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasisSet> BasisSets { get; set; }
        public virtual UsedParameter UsedParameter { get; set; }
    }
}
