//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    
    public enum WellheadComponentEnum : short
    {
        ValveType1 = 1,
        ValveType2 = 2,
        ValveType3 = 3,
        Pipe = 4,
        Flange = 5,
        Goathead = 6,
        Nut = 7,
        Other = 8
    }
}
