//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeismosDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellheadCoordinate
    {
        public System.Guid Id { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double KB { get; set; }
        public string CoordinateSystem { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
    
        public virtual Wellhead Wellhead { get; set; }
    }
}
